import { ApplicationState } from '../application.state';
import { TypecodesActions } from '../../core/typecodes/typecodes-actions';
import { TicketActions } from '../ticket-store/ticket-actions';.
import { TicketService } from '../ticket.service';
import { TicketModel, TicketTestModel } from '../models/ticket.model';
import { Component, Input, Output, OnInit, EventEmitter } from '@angular/core';
import * as types from '../models/types.model';
import { TypeCode } from '../models/type-code';
import { TicketAddModel } from '../models/ticket-add.model';
import { TypecodesService } from "app/core/typecodes/typecodes.service";
import { AllTypeCodesModel } from "app/core/typecodes/typecode.model";
import { Store } from '@ngrx/store';

@Component({
  selector: 'ticket-add',
  templateUrl: './ticket-add.component.html'
})
export class TicketAdd implements OnInit {
    //@Input()
    
    @Input()
    typecodes: AllTypeCodesModel;
    users: [];
    @Output()
    newTicket: TicketAddModel;
    addTicket = new EventEmitter();
    //subComponent = 'email';
    typecodes$: Observable<AllTypeCodesModel>;

   constructor(
     private typecodeService: TypecodesService, 
     private typecodesActions: TypecodesActions,
     private ticketActions: TicketActions,
     private store: Store<ApplicationState>) { 
       this.typecodes$ = store.select(this.typecodesSelector);
      }

    ngOnInit() {
      this.store.dispatch(this.typecodesActions.getAllTypecodes());
      console.log("newTicket",this.newTicket);
      this.newTicket = {
        summary: "",
        requesterId: null,
        ownerId: null,
        causeId: 3,
        statusId: 1,
        priorityId: 3,
        originId: null,
        categoryId: null,
        subcategoryId: null,
        isConfidential: false
      }
      this.typecodes$.subscribe((x) => this.typecodes = x);
      this.users = [
        {'name':'Aaron Gaspard', 'id':1},
{'name':'Adam Behrendt', 'id':3},
{'name':'Adam Nagorski', 'id':4},
{'name':'Afigo Fadahunsi', 'id':5},
{'name':'Agelo Reppas', 'id':6},
{'name':'Akin Alabi', 'id':7},
{'name':'Akinwale Collins', 'id':8},
{'name':'Alan Clements', 'id':9},
{'name':'Alan Vickery', 'id':10},
{'name':'Alex Espinoza', 'id':11},
{'name':'Alex Harrell', 'id':12},
{'name':'Alex Potente', 'id':13},
{'name':'Alex Potts', 'id':14},
{'name':'Alex Shilliday', 'id':15},
{'name':'Alexandra Block', 'id':17},
{'name':'Alfred Warrington', 'id':18},
{'name':'Alice Estipona', 'id':19},
{'name':'Alice Serko', 'id':20},
{'name':'Alisha Vance', 'id':21},
{'name':'Alison Beanum', 'id':22},
{'name':'Alison Thompson', 'id':23},
{'name':'Amanda Henderson', 'id':25},
{'name':'Amee Mikacich', 'id':26},
{'name':'Ammanual Luba', 'id':27},
{'name':'Amy Beecham', 'id':28},
{'name':'Amy Brittain', 'id':29},
{'name':'Andre Graf', 'id':30},
{'name':'Andrea Gaspard', 'id':31},
{'name':'Andrew Milne', 'id':32},
{'name':'Andrew Port', 'id':33},
{'name':'Andrew Sutherlin', 'id':34},
{'name':'Andromeda Butler', 'id':35},
{'name':'Angel Santiago', 'id':36},
{'name':'Angela Dunn', 'id':37},
{'name':'Angela Lansford', 'id':38},
{'name':'Angie Buchanan', 'id':39},
{'name':'Angie Liberty', 'id':40},
{'name':'Anjuli Cargain', 'id':42},
{'name':'Ann Bolen', 'id':43},
{'name':'Ann-Marie Tidwell', 'id':44},
{'name':'Anna Shimko', 'id':45},
{'name':'Anna M. Perez', 'id':46},
{'name':'Anne-Marie Rutledge', 'id':47},
{'name':'Annie Tualla', 'id':48},
{'name':'Anthony Anscombe', 'id':49},
{'name':'Anthony Varnado', 'id':50},
{'name':'Anurita Varma', 'id':51},
{'name':'Arameh O\'Boyle', 'id':52},
{'name':'Arthur Yee', 'id':53},
{'name':'Asha Mathai', 'id':54},
{'name':'Ashley Milnes', 'id':55},
{'name':'Azra Dracic', 'id':57},
{'name':'Barbara Chaney', 'id':58},
{'name':'Barbara Chasty', 'id':59},
{'name':'Barbara Dezelle', 'id':60},
{'name':'Barbara Fergerson', 'id':61},
{'name':'Barbara Miller', 'id':62},
{'name':'Barbara Riedel-O\'Leary', 'id':63},
{'name':'Barbara Werther', 'id':64},
{'name':'Barry Mesher', 'id':65},
{'name':'Beach Kuhl', 'id':66},
{'name':'Ben Walberg', 'id':67},
{'name':'Bernadette Lawson', 'id':68},
{'name':'Berridge Marsh', 'id':69},
{'name':'Beth Dressel', 'id':70},
{'name':'Beth Yoffie', 'id':71},
{'name':'Bethann Brandecker', 'id':72},
{'name':'Betsy Doyle', 'id':73},
{'name':'Blane Olmos', 'id':74},
{'name':'Bob Beyer', 'id':75},
{'name':'Bob Meyers', 'id':76},
{'name':'Brad Buchanan', 'id':77},
{'name':'Brandon Summers', 'id':78},
{'name':'Brenda Barham', 'id':79},
{'name':'Brenda Jansen', 'id':80},
{'name':'Brian Bakale', 'id':81},
{'name':'Brian Harrison', 'id':83},
{'name':'Brian Lowe', 'id':84},
{'name':'Brian Monroe', 'id':85},
{'name':'Brian Murphy', 'id':86},
{'name':'Brian Zeringer', 'id':87},
{'name':'Brittney Johnson', 'id':88},
{'name':'Bruce Celebrezze', 'id':89},
{'name':'Bruce McLeod', 'id':90},
{'name':'Bruce Wold', 'id':91},
{'name':'Byron Cantuna', 'id':92},
{'name':'Caitlin Conyers', 'id':93},
{'name':'Cameron Hill', 'id':94},
{'name':'Cameron Lue Sang', 'id':95},
{'name':'Cara Vecchione', 'id':96},
{'name':'Caran Smith', 'id':97},
{'name':'Carlos Lang', 'id':98},
{'name':'Carol Brophy', 'id':99},
{'name':'Carol Gerner', 'id':100},
{'name':'Carolina Espinoza', 'id':101},
{'name':'Caroline Mankey', 'id':102},
{'name':'Carrie Scott', 'id':103},
{'name':'Casey Schiano', 'id':104},
{'name':'Catherine Robb', 'id':105},
{'name':'Cathy Sugayan', 'id':106},
{'name':'Celeste Zamudio', 'id':107},
{'name':'Celina Curry', 'id':108},
{'name':'Cerwin Arcilla', 'id':109},
{'name':'Charles Brewster', 'id':110},
{'name':'Charles Davant', 'id':111},
{'name':'Charles Hurst', 'id':113},
{'name':'Charlotte Cook', 'id':114},
{'name':'Chelsea Trotter', 'id':115},
{'name':'Cheri While', 'id':116},
{'name':'Cherie Helton', 'id':117},
{'name':'Cherie L. Zeier', 'id':118},
{'name':'Cheryl Morris', 'id':119},
{'name':'Cheryl Slaughter', 'id':120},
{'name':'Chip Davis', 'id':121},
{'name':'Chris Burton', 'id':122},
{'name':'Chris Marks', 'id':123},
{'name':'Chris Morris', 'id':124},
{'name':'Chris Weldon', 'id':125},
{'name':'Christie Kirchenbauer', 'id':126},
{'name':'Christina Vargas', 'id':127},
{'name':'Christine Johnson', 'id':128},
{'name':'Christine Shores', 'id':129},
{'name':'Christopher Collings', 'id':130},
{'name':'Christopher Hall', 'id':131},
{'name':'Christopher Keale', 'id':132},
{'name':'Christopher Losquadro', 'id':133},
{'name':'Christopher Norton', 'id':135},
{'name':'Christopher Novak', 'id':136},
{'name':'Christopher R. Farnsworth', 'id':137},
{'name':'Cindy Akehurst', 'id':138},
{'name':'Cinthia Motley', 'id':139},
{'name':'Claire Cortner', 'id':140},
{'name':'Clay Abernathy', 'id':141},
{'name':'Clinton Van Dyke', 'id':142},
{'name':'Colin Nguyen', 'id':143},
{'name':'Conor Foley', 'id':144},
{'name':'Cori Steinmann', 'id':146},
{'name':'Craig Barnes', 'id':147},
{'name':'Craig Peterson', 'id':148},
{'name':'Crystal Landes', 'id':149},
{'name':'Curtis Parvin', 'id':150},
{'name':'Cynthia Alm', 'id':151},
{'name':'Cynthia Cho', 'id':152},
{'name':'Cynthia Plevin', 'id':153},
{'name':'Cynthia Smith', 'id':154},
{'name':'DaNeisha Goode', 'id':155},
{'name':'Daniel Bryer', 'id':156},
{'name':'Daniel Lu', 'id':157},
{'name':'Daniel Pole', 'id':158},
{'name':'Daniel Salerno', 'id':159},
{'name':'Daniel D. Pole', 'id':160},
{'name':'Danielle Nelson', 'id':161},
{'name':'Danya Ahmed', 'id':163},
{'name':'Darlene Alt', 'id':164},
{'name':'David Allen', 'id':165},
{'name':'David Blow', 'id':166},
{'name':'David Brown', 'id':167},
{'name':'David Collins', 'id':168},
{'name':'David Covey', 'id':169},
{'name':'David DeBusschere', 'id':170},
{'name':'David Dorsen', 'id':171},
{'name':'David Humiston', 'id':172},
{'name':'David Kent', 'id':173},
{'name':'David Mancini', 'id':174},
{'name':'David Mesa', 'id':175},
{'name':'David Rhodes', 'id':177},
{'name':'Dawn Klein', 'id':179},
{'name':'Dawn Lyons', 'id':180},
{'name':'Dawn McCord', 'id':181},
{'name':'DCOS Reception', 'id':182},
{'name':'Dean McElroy', 'id':183},
{'name':'Dean Smith', 'id':184},
{'name':'Deborah Cohen', 'id':186},
{'name':'Deborah O\'Connor', 'id':187},
{'name':'Debra Beatty', 'id':188},
{'name':'Debra Lambdin', 'id':189},
{'name':'Dejanette Newsome', 'id':190},
{'name':'Delia Isvoranu', 'id':191},
{'name':'Dennis Murphy', 'id':193},
{'name':'Dennis Rolstad', 'id':194},
{'name':'Dennis Vega', 'id':195},
{'name':'Diana Karnes', 'id':196},
{'name':'Diana Lynn', 'id':197},
{'name':'Diane Janner', 'id':198},
{'name':'Diane Reinhard', 'id':199},
{'name':'Diane Williams', 'id':200},
{'name':'Diane Woolsey', 'id':201},
{'name':'Diane S. Clark', 'id':202},
{'name':'DiAnna Thimjon', 'id':203},
{'name':'Dirk Haarhoff', 'id':204},
{'name':'Doris Hammond', 'id':205},
{'name':'Doris LaBarca', 'id':206},
{'name':'Dorothy Williams', 'id':207},
{'name':'Douglas Collodel', 'id':208},
{'name':'Douglas MacPhail', 'id':209},
{'name':'DTI Dallas Office', 'id':210},
{'name':'Duncan Strachan', 'id':211},
{'name':'Earl Hagstrom', 'id':212},
{'name':'Eddie Pulido', 'id':213},
{'name':'Edward Smerdon', 'id':214},
{'name':'Edward Stumpp', 'id':215},
{'name':'Eileen McKillop', 'id':216},
{'name':'Eileen San Diego', 'id':217},
{'name':'Ekaterina Levy', 'id':218},
{'name':'Eliza Rodrigues', 'id':219},
{'name':'Elizabeth Brett', 'id':220},
{'name':'Elizabeth Pina', 'id':221},
{'name':'Elizabeth Sitcharungsi', 'id':222},
{'name':'Elizabeth Stack', 'id':223},
{'name':'Elizabeth Trittipo', 'id':224},
{'name':'Elizabeth Verano', 'id':225},
{'name':'Ellen Beach', 'id':226},
{'name':'Elliott Olson', 'id':227},
{'name':'Elsa Colon', 'id':228},
{'name':'Elsa Cruz', 'id':229},
{'name':'Elsa Jimenez', 'id':230},
{'name':'Emily Pattison', 'id':231},
{'name':'Emily Weissenberger', 'id':232},
{'name':'Emmett Carey', 'id':233},
{'name':'Eric Danoff', 'id':234},
{'name':'Eric Scheiner', 'id':235},
{'name':'Erica Lewis', 'id':237},
{'name':'Erica Smith', 'id':238},
{'name':'Erin Dardis', 'id':239},
{'name':'Erin Fraser', 'id':240},
{'name':'Erin Lehnherr', 'id':241},
{'name':'Eryk Gettell', 'id':242},
{'name':'Eugene Brown Jr.', 'id':243},
{'name':'Eugene Elsbree', 'id':244},
{'name':'Evelyn De Jesus', 'id':245},
{'name':'Frank Gaddy', 'id':247},
{'name':'Fred Smith', 'id':248},
{'name':'Frederick Baker', 'id':249},
{'name':'Gary Sheppard', 'id':250},
{'name':'George Frank', 'id':251},
{'name':'George McCall', 'id':252},
{'name':'Gerald Duffy', 'id':253},
{'name':'Gilbert Lee', 'id':254},
{'name':'Gina Araya', 'id':255},
{'name':'Ginger Dicke', 'id':256},
{'name':'Glenn Nevils', 'id':257},
{'name':'Gloria Zwibel', 'id':258},
{'name':'Gregg Dulik', 'id':259},
{'name':'Gregory Halliday', 'id':260},
{'name':'Gregory Lahr', 'id':261},
{'name':'Gregory Read', 'id':262},
{'name':'Guy Cabral', 'id':264},
{'name':'Hall Marston', 'id':265},
{'name':'Heather Davis', 'id':266},
{'name':'Heather Hartkopp', 'id':267},
{'name':'Heather Zacharia', 'id':268},
{'name':'Hedwig Bachler', 'id':269},
{'name':'Hilary Rowen', 'id':270},
{'name':'Hollie McDaniel', 'id':271},
{'name':'Holly Tamisiea', 'id':272},
{'name':'Ileana Castellon', 'id':273},
{'name':'Ivan Terranova', 'id':274},
{'name':'Jaime Vallejo', 'id':275},
{'name':'James Baffa', 'id':276},
{'name':'James Brown', 'id':277},
{'name':'James Cagney', 'id':278},
{'name':'James Fang', 'id':280},
{'name':'James Gault', 'id':281},
{'name':'James Keale', 'id':282},
{'name':'James Kopacka', 'id':283},
{'name':'James Kuhne', 'id':284},
{'name':'James Marissen', 'id':285},
{'name':'James Mink', 'id':286},
{'name':'James Tamulski', 'id':290},
{'name':'James Wangelin', 'id':291},
{'name':'James J.S. Holmes', 'id':292},
{'name':'James M. Steere', 'id':293},
{'name':'Janet Proudfoot', 'id':295},
{'name':'Janezza Febrero', 'id':296},
{'name':'Jara Stewart', 'id':297},
{'name':'Jared Victoria', 'id':298},
{'name':'Jason Chorley', 'id':299},
{'name':'Jason Vento', 'id':300},
{'name':'Javier Hernandez', 'id':301},
{'name':'Jean Ann Underwood', 'id':302},
{'name':'Jeannine C. Jacobson', 'id':303},
{'name':'Jeff Hudgens', 'id':304},
{'name':'Jeffrey Bake', 'id':305},
{'name':'Jeffrey Castillo', 'id':306},
{'name':'Jemma Dunn', 'id':307},
{'name':'Jenna Nguyen', 'id':308},
{'name':'Jenni Katzer', 'id':309},
{'name':'Jennifer Broda', 'id':310},
{'name':'Jennifer Greenaway', 'id':311},
{'name':'Jennifer Moulder', 'id':312},
{'name':'Jennifer Teran', 'id':313},
{'name':'Jennifer Walker O\'Sullivan', 'id':314},
{'name':'Jerald Prater', 'id':315},
{'name':'Jini Anderson', 'id':316},
{'name':'JoAnn Dalrymple', 'id':317},
{'name':'Joanne Heffron Jones', 'id':318},
{'name':'JoAnne Tracey', 'id':319},
{'name':'Joel Kane', 'id':320},
{'name':'John Blancett', 'id':322},
{'name':'John Gherini', 'id':323},
{'name':'John McGinty', 'id':324},
{'name':'John Stephens', 'id':325},
{'name':'Johnny Wong', 'id':326},
{'name':'Jon Arneson', 'id':327},
{'name':'Jonathan Geremia', 'id':328},
{'name':'Jonathan Hayes', 'id':329},
{'name':'Jonathan Rodriguez', 'id':330},
{'name':'Joneis Phan', 'id':331},
{'name':'Jordan Rothman', 'id':332},
{'name':'Joseph Cardenas', 'id':333},
{'name':'Joseph Falgiani', 'id':334},
{'name':'Joseph Fanning', 'id':335},
{'name':'Joseph Larsen', 'id':336},
{'name':'Joseph Pastino', 'id':337},
{'name':'Joseph Powers', 'id':338},
{'name':'Joshua Clark', 'id':340},
{'name':'Joshua Lance', 'id':341},
{'name':'Jovana Vujovic', 'id':342},
{'name':'Juan Torres', 'id':343},
{'name':'Jude Hickland', 'id':344},
{'name':'Judith Hendrickson', 'id':345},
{'name':'June Hughes', 'id':346},
{'name':'Justin Levy', 'id':347},
{'name':'Kanika Corley', 'id':348},
{'name':'Kara DiBiasio', 'id':349},
{'name':'Karen Griffith', 'id':350},
{'name':'Karen Maupin', 'id':351},
{'name':'Karen Morrish', 'id':352},
{'name':'Karen Nellor', 'id':353},
{'name':'Karen Snead', 'id':354},
{'name':'Karen Stewart', 'id':355},
{'name':'Karolina Dilaveri', 'id':357},
{'name':'Katelin O\'Rourke Gorman', 'id':358},
{'name':'Katharine Essick', 'id':359},
{'name':'Kathleen Whang', 'id':360},
{'name':'Kathryn Richter', 'id':361},
{'name':'Kathy Kubat', 'id':362},
{'name':'Kathy Noga', 'id':363},
{'name':'Kathy Rollins', 'id':364},
{'name':'Kayleigh Stout', 'id':365},
{'name':'Kecia Barrett-Callahan', 'id':366},
{'name':'Kelly Belnick', 'id':368},
{'name':'Kelly Green', 'id':369},
{'name':'Kelly Olson', 'id':370},
{'name':'Kendra Canape', 'id':371},
{'name':'Kenneth Jones', 'id':372},
{'name':'Keri Wood', 'id':373},
{'name':'Kevin Dunne', 'id':374},
{'name':'Kevin Gilliland', 'id':375},
{'name':'Kevin Lashley', 'id':376},
{'name':'Khadir Phar', 'id':377},
{'name':'Kim Christenson', 'id':378},
{'name':'Kim Hendrix', 'id':379},
{'name':'Kim Wlodarczak', 'id':380},
{'name':'Kimberly Campbell', 'id':381},
{'name':'Kimberly Cook', 'id':382},
{'name':'Kimberly Forrester', 'id':383},
{'name':'Kimberly Rice', 'id':384},
{'name':'Kimberly Steele', 'id':385},
{'name':'Kinnier Lastimosa', 'id':386},
{'name':'Kirk Jenkins', 'id':387},
{'name':'Krista Gutierrez', 'id':389},
{'name':'Kristen Gutierrez', 'id':390},
{'name':'Kristen Johnson', 'id':391},
{'name':'Kristie Wyble', 'id':392},
{'name':'LA Office Services', 'id':393},
{'name':'Ladd Cogan', 'id':394},
{'name':'Laura Flood', 'id':396},
{'name':'Laura Goodman', 'id':397},
{'name':'Laura Stephan', 'id':398},
{'name':'Laura Lee Prather', 'id':399},
{'name':'Laurie Kamaiko', 'id':400},
{'name':'Lavella Garner', 'id':401},
{'name':'Lawrence Klein', 'id':402},
{'name':'Lenell McCallum', 'id':403},
{'name':'Leo Ponseca', 'id':404},
{'name':'LeQuita Hodge', 'id':405},
{'name':'Lesa Lewis', 'id':406},
{'name':'Letisha Parker-Arroyo', 'id':407},
{'name':'Levon Sanossian', 'id':409},
{'name':'Lillian Stenfeldt', 'id':411},
{'name':'Linda Corbett', 'id':412},
{'name':'Linda Ehrhart', 'id':413},
{'name':'Linda Robinson', 'id':414},
{'name':'Linda Scavo', 'id':415},
{'name':'Linda Sturtevant', 'id':416},
{'name':'Lisa Caplan', 'id':417},
{'name':'Lisa Carroll', 'id':418},
{'name':'Lisa Goldberg', 'id':419},
{'name':'Lisa Henderson', 'id':420},
{'name':'Lisa Ramirez', 'id':421},
{'name':'Liz Hagerman', 'id':424},
{'name':'Liz Ruelas', 'id':425},
{'name':'Lois Johnson', 'id':426},
{'name':'Lori Chapin', 'id':427},
{'name':'Lori Gong', 'id':428},
{'name':'Lorna Moore', 'id':429},
{'name':'Lorraine Gallo', 'id':430},
{'name':'Lucy Dyson', 'id':431},
{'name':'Lucy Spencer', 'id':432},
{'name':'Luisa Pineda', 'id':433},
{'name':'Lynn Curry', 'id':434},
{'name':'Magaly Burgos', 'id':435},
{'name':'Maggie Watkins', 'id':436},
{'name':'Mahsa Soheil', 'id':437},
{'name':'Mara Hsiung', 'id':438},
{'name':'Marc Haas', 'id':439},
{'name':'Marc Koonin', 'id':440},
{'name':'Marcos Cancio', 'id':441},
{'name':'Margaret Arenas', 'id':442},
{'name':'Margaret Holm', 'id':443},
{'name':'Margaret Morasca', 'id':444},
{'name':'Margaret M. Masters', 'id':445},
{'name':'Maria Giardina', 'id':446},
{'name':'Maria Jardeleza', 'id':447},
{'name':'Maria Karos', 'id':448},
{'name':'Maria Tiegen', 'id':449},
{'name':'Marian Tighe-Krushinsky', 'id':450},
{'name':'Maricel Renigen', 'id':451},
{'name':'Marilyn Klinger', 'id':452},
{'name':'Marina Freyre', 'id':453},
{'name':'Mario Horwitz', 'id':455},
{'name':'Mario Marcelle', 'id':456},
{'name':'Mario Reyes', 'id':457},
{'name':'Marion Tate', 'id':458},
{'name':'Mark Anderson', 'id':459},
{'name':'Mark Chudleigh', 'id':460},
{'name':'Mark Hudson', 'id':462},
{'name':'Mark Kendall', 'id':463},
{'name':'Mark Killingsworth', 'id':464},
{'name':'Mark Miller', 'id':465},
{'name':'Mark Mitobe', 'id':466},
{'name':'Mark Nordike', 'id':467},
{'name':'Mark Schlemmer', 'id':468},
{'name':'Mark Smylie', 'id':469},
{'name':'Mark Wasef', 'id':471},
{'name':'Marlene Adelman', 'id':472},
{'name':'Marta Correa', 'id':473},
{'name':'Martin Healy', 'id':475},
{'name':'Martin O\'Leary', 'id':476},
{'name':'Mary Buckley', 'id':478},
{'name':'Mary Melle', 'id':479},
{'name':'Mary Jo Stringer', 'id':480},
{'name':'Maryam Meseha', 'id':481},
{'name':'Matt Knoth', 'id':482},
{'name':'Matthew Ferguson', 'id':483},
{'name':'Matthew Mazzola', 'id':485},
{'name':'Mayra Montalvo', 'id':487},
{'name':'Meegan Brooks', 'id':488},
{'name':'Meg Daday', 'id':489},
{'name':'Megan Molinaro', 'id':490},
{'name':'Melanie Gigliotti', 'id':491},
{'name':'Melinda Axel', 'id':492},
{'name':'Melissa Olive', 'id':493},
{'name':'Melodi Johnson', 'id':494},
{'name':'Meredith Philipp', 'id':495},
{'name':'Michael Bernick', 'id':496},
{'name':'Michael Bernstein', 'id':497},
{'name':'Michael Healy', 'id':498},
{'name':'Michael McKenzie', 'id':500},
{'name':'Michael Ruiz', 'id':501},
{'name':'Michael Sabino', 'id':502},
{'name':'Michael Satz', 'id':503},
{'name':'Michael Tanenbaum', 'id':504},
{'name':'Michael Topp', 'id':505},
{'name':'Michael Yim', 'id':507},
{'name':'Michael "Angelo" McCabe', 'id':508},
{'name':'Michael L. Fox', 'id':509},
{'name':'Michele Blay', 'id':510},
{'name':'Michelle Allred', 'id':511},
{'name':'Michelle Hood', 'id':512},
{'name':'Michelle Watson', 'id':513},
{'name':'Mike Dispensa', 'id':514},
{'name':'Mike Pipkin', 'id':515},
{'name':'Mirali Vazirinejad', 'id':517},
{'name':'Moises Melendez', 'id':518},
{'name':'Monica Mondragon', 'id':519},
{'name':'Nancy Zlateff', 'id':521},
{'name':'Naomi Vary', 'id':522},
{'name':'Natasha Fisher', 'id':523},
{'name':'Nathan Jones', 'id':524},
{'name':'Nathan Stewart', 'id':525},
{'name':'Nathaniel Mina', 'id':526},
{'name':'Neil Ramos', 'id':527},
{'name':'Neil Thomson', 'id':528},
{'name':'Nicholas Heldt', 'id':531},
{'name':'Nicholas Tucker', 'id':532},
{'name':'Nicholas Weiss', 'id':533},
{'name':'Nick Corte', 'id':534},
{'name':'Nick Miles', 'id':535},
{'name':'Nicole Born', 'id':536},
{'name':'Nicole Nielson-Pachkofsky', 'id':537},
{'name':'Nikki Ihnatiuk', 'id':538},
{'name':'Nora Wetzel', 'id':539},
{'name':'Norman Hopper', 'id':540},
{'name':'Norman Lau', 'id':541},
{'name':'Octavia Green', 'id':543},
{'name':'Oliver Rebollido', 'id':546},
{'name':'Oluoma Kas-Osoka', 'id':547},
{'name':'Pam Brogoto', 'id':548},
{'name':'Pamela Martin', 'id':549},
{'name':'Parisa Nikamalfard', 'id':550},
{'name':'Patricia Daza-Luu', 'id':551},
{'name':'Patricia Williamson', 'id':552},
{'name':'Patrick Kenney, Jr.', 'id':553},
{'name':'Patti Hosford', 'id':554},
{'name':'Paul Davidson', 'id':555},
{'name':'Paul Garverick', 'id':556},
{'name':'Paul Lahaderne', 'id':557},
{'name':'Paulina Borges', 'id':560},
{'name':'Peter Fabiankovic', 'id':562},
{'name':'Peter Horst', 'id':563},
{'name':'Phillip Jackson', 'id':565},
{'name':'Phyllis Flynn', 'id':566},
{'name':'Rachel Burd', 'id':567},
{'name':'Rachel Reynolds', 'id':568},
{'name':'Rachel Weitzman', 'id':569},
{'name':'Ralph Campillo', 'id':570},
{'name':'Ralph Feliciano', 'id':571},
{'name':'Ralph Guirgis', 'id':572},
{'name':'Ramón Abadin', 'id':573},
{'name':'Ramona Dorsey-Wade', 'id':574},
{'name':'Randall Block', 'id':575},
{'name':'Randall Wilson', 'id':576},
{'name':'Randy Mangubat', 'id':577},
{'name':'Raquel Navarroza', 'id':578},
{'name':'Raquel Negron', 'id':579},
{'name':'Raul Garcia', 'id':580},
{'name':'Raygine Francois', 'id':581},
{'name':'Raymond Friede', 'id':582},
{'name':'Rebecca Baumgartner', 'id':583},
{'name':'Rebecca Hull', 'id':584},
{'name':'Reena Khetani', 'id':585},
{'name':'Renga Thiagarajah', 'id':586},
{'name':'Rhamie Glade', 'id':587},
{'name':'Rhonda Gillis', 'id':588},
{'name':'Ricardo Small', 'id':589},
{'name':'Richard Booth', 'id':590},
{'name':'Richard Geddes', 'id':591},
{'name':'Robert Bohner', 'id':593},
{'name':'Robert Budelman', 'id':594},
{'name':'Robert Cain', 'id':595},
{'name':'Robert Eassa', 'id':596},
{'name':'Robert Gebhard', 'id':597},
{'name':'Robert Helfing', 'id':598},
{'name':'Robert Kum', 'id':599},
{'name':'Robert Towey', 'id':600},
{'name':'Robert Willis', 'id':602},
{'name':'Robert Zermeno, Jr.', 'id':603},
{'name':'Roberta J. Benson', 'id':604},
{'name':'Roger Gonzalez', 'id':606},
{'name':'Roger Sleight', 'id':607},
{'name':'Ron Gersten', 'id':608},
{'name':'Rosaisela Zarate', 'id':609},
{'name':'Rose DeLeon Carter', 'id':610},
{'name':'Rosemary Pereda', 'id':611},
{'name':'Roussy Brizuela', 'id':612},
{'name':'Ryan Arroyo', 'id':614},
{'name':'Ryan Harrison', 'id':616},
{'name':'Ryan McCord', 'id':617},
{'name':'Ryan Ortuno', 'id':618},
{'name':'Ryan Taylor', 'id':619},
{'name':'Ryan G. Kercher', 'id':620},
{'name':'Rynicia Wilson', 'id':621},
{'name':'Sabrina Smith', 'id':622},
{'name':'Sakina Murray', 'id':623},
{'name':'Salvatore Lento', 'id':624},
{'name':'Sandra Johnson', 'id':625},
{'name':'Sandra Ozuna', 'id':626},
{'name':'Sara Inman', 'id':627},
{'name':'Sara Robison', 'id':628},
{'name':'Sarah Bramlett', 'id':629},
{'name':'Sarah Gover', 'id':630},
{'name':'Sarah Hennessy', 'id':631},
{'name':'Sarah Owens', 'id':632},
{'name':'Sarah Rixson', 'id':633},
{'name':'Sarah Sepe', 'id':634},
{'name':'Savanna Darby', 'id':635},
{'name':'Scott Downes', 'id':636},
{'name':'Scott Gronseth', 'id':637},
{'name':'Scott Mroz', 'id':638},
{'name':'Sean Patterson', 'id':639},
{'name':'Sean Rawls', 'id':640},
{'name':'Sean Simpson', 'id':641},
{'name':'Server SF-INTRANET-T1', 'id':642},
{'name':'Server SF-MONITOR-01', 'id':643},
{'name':'Seth McCauley', 'id':644},
{'name':'SF Copy Center', 'id':645},
{'name':'SF Mail Room', 'id':646},
{'name':'Shane Wesley', 'id':647},
{'name':'Sharon O\'Connell', 'id':648},
{'name':'Sharon Reinhart', 'id':649},
{'name':'Sharra McIntosh', 'id':650},
{'name':'Shaudee Navid', 'id':651},
{'name':'Shaun Bean', 'id':652},
{'name':'Shawn Martin', 'id':653},
{'name':'Shawna Harkins', 'id':654},
{'name':'Shayla Taulbee', 'id':655},
{'name':'Sheila Howell', 'id':656},
{'name':'Sheila Searcy', 'id':657},
{'name':'Shelby Reams', 'id':658},
{'name':'Sheryl Rosenberg', 'id':659},
{'name':'Shweta Maheshwari', 'id':660},
{'name':'Sidney Dowell', 'id':661},
{'name':'Silvia Alioto', 'id':662},
{'name':'Sindy Fleeger', 'id':663},
{'name':'Sondra Sylva', 'id':664},
{'name':'Sonja Di Mondi', 'id':665},
{'name':'Soo Kim', 'id':666},
{'name':'Stacey Phillips', 'id':667},
{'name':'Stephanie DeClue', 'id':668},
{'name':'Stephanie Manjarrez', 'id':669},
{'name':'Stephanie Moynihan', 'id':670},
{'name':'Stephanie Perkins', 'id':671},
{'name':'Stephanie Sheridan', 'id':672},
{'name':'Stephanie Stephens', 'id':673},
{'name':'Stephen Green', 'id':674},
{'name':'Stephen Jones', 'id':675},
{'name':'Stephen Shaw', 'id':676},
{'name':'Steve Burke', 'id':677},
{'name':'Steven Di Saia', 'id':678},
{'name':'Steven Roland', 'id':679},
{'name':'Steven Wasserman', 'id':680},
{'name':'Sunny Shapiro', 'id':681},
{'name':'Susan Forsthoff', 'id':682},
{'name':'Susan Sullivan', 'id':683},
{'name':'Susan Vargas', 'id':684},
{'name':'Susan V. Watson', 'id':685},
{'name':'Sushu Wang', 'id':686},
{'name':'Suzanne Horn', 'id':687},
{'name':'Suzaye Junod', 'id':688},
{'name':'T.J. Quick', 'id':689},
{'name':'Tahamina Martin', 'id':690},
{'name':'Talicia Smith', 'id':691},
{'name':'Tanya Garrett', 'id':692},
{'name':'Tanya Palmer', 'id':693},
{'name':'Tara Clancy', 'id':694},
{'name':'Tasha Martin', 'id':695},
{'name':'Teresa Walters', 'id':696},
{'name':'Thomas Blaber', 'id':697},
{'name':'Thomas Jennings', 'id':698},
{'name':'Thomas Lord', 'id':699},
{'name':'Thomas McGinty', 'id':700},
{'name':'Thomas Orofino', 'id':701},
{'name':'Thomas Robertson', 'id':702},
{'name':'Tiffany Alexander', 'id':703},
{'name':'Tiffany Gaines', 'id':704},
{'name':'Tiffiney Rogers', 'id':705},
{'name':'Tim Lozensky', 'id':706},
{'name':'Timothy Freeman', 'id':707},
{'name':'Timothy Kevane', 'id':708},
{'name':'Tina Sanders', 'id':709},
{'name':'Tom Everitt', 'id':710},
{'name':'Tomasz Grodzki', 'id':711},
{'name':'Tony Antico', 'id':712},
{'name':'Traci Ribeiro', 'id':714},
{'name':'Traci Wright', 'id':715},
{'name':'Travis Goodsell', 'id':716},
{'name':'Travis Martinez', 'id':717},
{'name':'Trish Stevens-Marwedel', 'id':718},
{'name':'Tristan Hall', 'id':719},
{'name':'Troy McMahan', 'id':720},
{'name':'Valerie Acevedo-Luna', 'id':721},
{'name':'Valerie Hosek', 'id':722},
{'name':'Valerie Shea', 'id':723},
{'name':'Vance Wittie', 'id':724},
{'name':'Veena Mitchell', 'id':725},
{'name':'Veronica Goodwin', 'id':726},
{'name':'Veronica Zavala', 'id':727},
{'name':'Vicki Bailey', 'id':728},
{'name':'Victor Pellicia', 'id':729},
{'name':'Victoria Brown', 'id':730},
{'name':'Vincent Page', 'id':732},
{'name':'Virus Notification', 'id':733},
{'name':'Virus Notifications', 'id':734},
{'name':'Vivian Borroto', 'id':735},
{'name':'Vivian Louden', 'id':736},
{'name':'W. Bruce Wold', 'id':737},
{'name':'W. Neil Rambin', 'id':738},
{'name':'Walter Owens', 'id':739},
{'name':'Wanda Adams', 'id':740},
{'name':'Warren Krauss', 'id':741},
{'name':'Wayne Wolff', 'id':742},
{'name':'Wayne B. Mason', 'id':743},
{'name':'Wendi Pearce', 'id':744},
{'name':'William Brennan', 'id':745},
{'name':'William Judge', 'id':746},
{'name':'William Liu', 'id':747},
{'name':'William Miedel', 'id':748},
{'name':'Yenisey Gonzalez', 'id':749},
{'name':'Yogen Joshi', 'id':750}
      ]
    }

    typecodesSelector(state: ApplicationState): AllTypeCodesModel {
        if (state.typecodesStoreData) {
            return {
                categoryTypes: state.typecodesStoreData.categories,
                priorityTypes: state.typecodesStoreData.priorities,
                originTypes: state.typecodesStoreData.origins,
                causeTypes: state.typecodesStoreData.causes,
                statusTypes: state.typecodesStoreData.statuses,
                subcategoryTypes: state.typecodesStoreData.subcategories
            };
        }
    }
    postTicket(newTicket: TicketAddModel) {
        console.log("newTicket=",newTicket);
        this.addTicket.next(newTicket);
        this.store.dispatch(this.ticketActions.addTicket(newTicket))
        this.newTicket = {
            summary: "",
            requesterId: null,
            ownerId: null,
            causeId: 3,
            statusId: 1,
            priorityId: 3,
            originId: null,
            categoryId: null,
            subcategoryId: null,
            isConfidential: false
        };
    }
}
